name: DecodingNms
version: "1.0"
api-version: "1.17"
authors: [ 'Apple' ]
main: apple.nms.decoding.PluginDecodingNms
description: decodes nms into something more readable
softdepend:
  - LoadDependencies